# yaml-language-server: $schema=https://coderabbit.ai/integrations/coderabbit-overrides.v2.json

language: "ja"
early_access: false
reviews:
  high_level_summary: false
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/.xml"
  path_instructions:
    - path: "**/.tsx"
      instructions: |
        "Review the JavaScript code for conformity with the Google JavaScript style guide, highlighting any deviations. and let me know your ChatGPT model version"
    - path: "tests/**.*"
      instructions: |
        "Assess the unit test code employing the Mocha testing framework. Confirm that:
        - The tests adhere to Mocha's established best practices.
        - Test descriptions are sufficiently detailed to clarify the purpose of each test."
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "main"
      - "feat"
      - "feat/coderabbit-yml"
chat:
  auto_reply: true
