name: Remove branch

on:
  pull_request:
    types: [ closed ]

jobs:
  close_job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Delete closed PR branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          numbers: ${{ github.event.pull_request.number }}
